import { type ApiKey } from '../../src/services/apiService'

export namespace CustomerApiKeyFixtures {
  export function getDummyKeys (): ApiKey[] {
    const baseKey: ApiKey = {
      CustomerApiKeyId: 'HUBRJFSFEKJTXT1V0R70',
      ApiGatewayId: 'ASKHSDF-SDAKH-SDAKFH-SDAFKS',
      UsagePlanId: '1ju1kk',
      Secret: 'VerySecretValue',
      Enabled: true,
      Description: 'Autogenerated key',
      FpoId: '345897354',
      CreatedAt: '2024-04-10T16:11:45.714Z',
      UpdatedAt: '2024-04-10T16:11:45.715Z'
    }

    return [
      baseKey,
      {
        ...baseKey,
        CustomerApiKeyId: 'HUBRJFSFEKJTDR67F',
        Description: 'Another autogenerated key'
      },
      {
        ...baseKey,
        CustomerApiKeyId: 'HUBRJFSFEDTTXT1V7R70',
        Description: 'Another autogenerated key'
      },
      {
        ...baseKey,
        CustomerApiKeyId: 'HUBRJFSFDEFHXT1V0R70',
        Description: 'Another autogenerated key',
        Enabled: false
      }
      ]
  }
}
