export class CustomerApiKeyFixtures {
    static getDummyKeys(): any[] {
        const baseKey = {
            CustomerApiKeyId: 'HUBRJFSFEKJTXT1V0R70',
            ApiGatewayId: '',
            UsagePlanId: '1ju1kk',
            Secret: 'VerySecretValue',
            Enabled: true,
            Description: 'Autogenerated key',
            FpoId: '345897354',
            CreatedAt: '2024-04-10T16:11:45.714Z',
            UpdatedAt: '2024-04-10T16:11:45.715Z',
            Saved: false
        };

        return [
            baseKey,
            {
                ...baseKey,
                CustomerApiKeyId: 'ANOTHERUNIQUEKEYID',
                Description: 'Another autogenerated key'
            }
        ];
    }
}
